### ISSUE TITLE
special accents like ^ don't display with Qt6: xkbcommon: ERROR: couldn't find a Compose file for locale "fr_FR.UTF-8"

### ISSUE THREAD

**Issue by be1** [canonical/mesa-2404#23]
While running the `redrose`  snap (core24) with LANG=fr_FR.UTF-8, accents needing a composition, like î or ï, don't display for newly typed text.
The following error is reported while typing such text:
```
xkbcommon: ERROR: couldn't find a Compose file for locale "fr_FR.UTF-8" (mapped to "fr_FR.UTF-8")
qt.xkb.compose: failed to create compose table
```

For reference, see snap description of `redrose` : https://github.com/be1/redrose/blob/main/snap/snapcraft.yaml

**Comment by Saviq** [comment]
@be1 the mesa snap does not have XKB in it, you need this in your snap:

```yaml
environment:
  XKB_CONFIG_DIR: $SNAP/usr/share/X11/xkb

parts:
  xkb:
    stage-packages:
    - xkb-data
```
